// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding::donation_refunded {

    use sui::object;
    use sui_crowdfunding::project::{Self, DonationRefunded};

    public fun id(donation_refunded: &DonationRefunded): object::ID {
        project::donation_refunded_id(donation_refunded)
    }

    public fun donator(donation_refunded: &DonationRefunded): address {
        project::donation_refunded_donator(donation_refunded)
    }

    public fun amount(donation_refunded: &DonationRefunded): u64 {
        project::donation_refunded_amount(donation_refunded)
    }

}
