// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding::donation_received {

    use sui::object;
    use sui_crowdfunding::project::{Self, DonationReceived};

    public fun id(donation_received: &DonationReceived): object::ID {
        project::donation_received_id(donation_received)
    }

    public fun donator(donation_received: &DonationReceived): address {
        project::donation_received_donator(donation_received)
    }

    public fun amount(donation_received: &DonationReceived): u64 {
        project::donation_received_amount(donation_received)
    }

}
