// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding::project_started {

    use sui::object;
    use sui_crowdfunding::project::{Self, ProjectStarted};

    public fun id(project_started: &ProjectStarted): object::ID {
        project::project_started_id(project_started)
    }

    public fun deadline(project_started: &ProjectStarted): u64 {
        project::project_started_deadline(project_started)
    }

}
