// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding::project_created {

    use std::option;
    use std::string::String;
    use sui::object::{Self, ID};
    use sui_crowdfunding::project::{Self, ProjectCreated};

    public fun id(project_created: &ProjectCreated): option::Option<object::ID> {
        project::project_created_id(project_created)
    }

    public fun platform_id(project_created: &ProjectCreated): ID {
        project::project_created_platform_id(project_created)
    }

    public fun owner(project_created: &ProjectCreated): address {
        project::project_created_owner(project_created)
    }

    public fun title(project_created: &ProjectCreated): String {
        project::project_created_title(project_created)
    }

    public fun description(project_created: &ProjectCreated): String {
        project::project_created_description(project_created)
    }

    public fun target(project_created: &ProjectCreated): u64 {
        project::project_created_target(project_created)
    }

    public fun image(project_created: &ProjectCreated): String {
        project::project_created_image(project_created)
    }

    public fun token_type(project_created: &ProjectCreated): String {
        project::project_created_token_type(project_created)
    }

}
