// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module sui_crowdfunding::project_updated {

    use std::string::String;
    use sui::object;
    use sui_crowdfunding::project::{Self, ProjectUpdated};

    public fun id(project_updated: &ProjectUpdated): object::ID {
        project::project_updated_id(project_updated)
    }

    public fun title(project_updated: &ProjectUpdated): String {
        project::project_updated_title(project_updated)
    }

    public fun description(project_updated: &ProjectUpdated): String {
        project::project_updated_description(project_updated)
    }

    public fun target(project_updated: &ProjectUpdated): u64 {
        project::project_updated_target(project_updated)
    }

    public fun image(project_updated: &ProjectUpdated): String {
        project::project_updated_image(project_updated)
    }

}
